package prometheus

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/fregataa/aami/internal/config"
)

const prometheusConfigTemplate = `# Generated by AAMI - Do not edit manually
global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - '/etc/aami/rules/*.yaml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:{{ .Prometheus.Port }}']

  - job_name: 'node'
    file_sd_configs:
      - files:
          - '/var/lib/aami/targets/nodes.json'
        refresh_interval: 30s

  - job_name: 'dcgm'
    file_sd_configs:
      - files:
          - '/var/lib/aami/targets/dcgm.json'
        refresh_interval: 30s
`

// GenerateConfig generates the Prometheus configuration file
func GenerateConfig(cfg *config.Config, outputPath string) error {
	tmpl, err := template.New("prometheus").Parse(prometheusConfigTemplate)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("create file: %w", err)
	}
	defer f.Close()

	return tmpl.Execute(f, cfg)
}

// Target represents a Prometheus scrape target
type Target struct {
	Targets []string          `json:"targets"`
	Labels  map[string]string `json:"labels"`
}

// GenerateNodeTargets generates the file_sd JSON for node_exporter
func GenerateNodeTargets(nodes []config.NodeConfig, outputDir string) error {
	var targets []Target

	for _, node := range nodes {
		target := Target{
			Targets: []string{fmt.Sprintf("%s:9100", node.IP)},
			Labels: map[string]string{
				"node": node.Name,
				"job":  "node",
			},
		}

		// Add custom labels
		for k, v := range node.Labels {
			target.Labels[k] = v
		}

		targets = append(targets, target)
	}

	return writeTargets(targets, filepath.Join(outputDir, "nodes.json"))
}

// GenerateDCGMTargets generates the file_sd JSON for dcgm_exporter
func GenerateDCGMTargets(nodes []config.NodeConfig, outputDir string) error {
	var targets []Target

	for _, node := range nodes {
		target := Target{
			Targets: []string{fmt.Sprintf("%s:9400", node.IP)},
			Labels: map[string]string{
				"node": node.Name,
				"job":  "dcgm",
			},
		}

		// Add custom labels
		for k, v := range node.Labels {
			target.Labels[k] = v
		}

		targets = append(targets, target)
	}

	return writeTargets(targets, filepath.Join(outputDir, "dcgm.json"))
}

// GenerateAllTargets generates all target files
func GenerateAllTargets(nodes []config.NodeConfig, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("create targets directory: %w", err)
	}

	if err := GenerateNodeTargets(nodes, outputDir); err != nil {
		return fmt.Errorf("generate node targets: %w", err)
	}

	if err := GenerateDCGMTargets(nodes, outputDir); err != nil {
		return fmt.Errorf("generate dcgm targets: %w", err)
	}

	return nil
}

func writeTargets(targets []Target, path string) error {
	data, err := json.MarshalIndent(targets, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal targets: %w", err)
	}

	return os.WriteFile(path, data, 0644)
}
