package service

import (
	"context"
	"errors"

	"github.com/fregataa/aami/config-server/internal/action"
	"github.com/fregataa/aami/config-server/internal/domain"
	domainerrors "github.com/fregataa/aami/config-server/internal/errors"
	"github.com/fregataa/aami/config-server/internal/repository"
)

// AlertTemplateService handles business logic for alert templates
type AlertTemplateService struct {
	templateRepo repository.AlertTemplateRepository
}

// NewAlertTemplateService creates a new AlertTemplateService
func NewAlertTemplateService(templateRepo repository.AlertTemplateRepository) *AlertTemplateService {
	return &AlertTemplateService{
		templateRepo: templateRepo,
	}
}

// Create creates a new alert template
func (s *AlertTemplateService) Create(ctx context.Context, act action.CreateAlertTemplate) (action.AlertTemplateResult, error) {
	// Validate severity
	if !act.Severity.IsValid() {
		return action.AlertTemplateResult{}, domainerrors.NewValidationError("severity", "invalid severity value")
	}

	// Check if template with same name already exists
	existing, err := s.templateRepo.GetByName(ctx, act.Name)
	if err == nil && existing != nil {
		return action.AlertTemplateResult{}, domainerrors.ErrAlreadyExists
	}
	if err != nil && !errors.Is(err, domainerrors.ErrNotFound) {
		return action.AlertTemplateResult{}, err
	}

	template := &domain.AlertTemplate{
		// ID is intentionally left empty - will be auto-generated by database (UUID)
		Name:          act.Name,
		Description:   act.Description,
		Severity:      act.Severity,
		QueryTemplate: act.QueryTemplate,
		DefaultConfig: act.DefaultConfig,
	}

	if err := s.templateRepo.Create(ctx, template); err != nil {
		return action.AlertTemplateResult{}, err
	}

	return action.NewAlertTemplateResult(template), nil
}

// GetByID retrieves an alert template by ID
func (s *AlertTemplateService) GetByID(ctx context.Context, id string) (action.AlertTemplateResult, error) {
	template, err := s.templateRepo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, domainerrors.ErrNotFound) {
			return action.AlertTemplateResult{}, domainerrors.ErrNotFound
		}
		return action.AlertTemplateResult{}, err
	}
	return action.NewAlertTemplateResult(template), nil
}

// Update updates an existing alert template
func (s *AlertTemplateService) Update(ctx context.Context, id string, act action.UpdateAlertTemplate) (action.AlertTemplateResult, error) {
	template, err := s.templateRepo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, domainerrors.ErrNotFound) {
			return action.AlertTemplateResult{}, domainerrors.ErrNotFound
		}
		return action.AlertTemplateResult{}, err
	}

	if act.Name != nil {
		template.Name = *act.Name
	}

	if act.Description != nil {
		template.Description = *act.Description
	}

	if act.Severity != nil {
		if !act.Severity.IsValid() {
			return action.AlertTemplateResult{}, domainerrors.NewValidationError("severity", "invalid severity value")
		}
		template.Severity = *act.Severity
	}

	if act.QueryTemplate != nil {
		template.QueryTemplate = *act.QueryTemplate
	}

	if act.DefaultConfig != nil {
		template.DefaultConfig = *act.DefaultConfig
	}

	if err := s.templateRepo.Update(ctx, template); err != nil {
		return action.AlertTemplateResult{}, err
	}

	return action.NewAlertTemplateResult(template), nil
}

// Delete performs soft delete on an alert template
func (s *AlertTemplateService) Delete(ctx context.Context, id string) error {
	_, err := s.templateRepo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, domainerrors.ErrNotFound) {
			return domainerrors.ErrNotFound
		}
		return err
	}

	return s.templateRepo.Delete(ctx, id)
}

// Purge permanently removes an alert template (hard delete, admin operation)
func (s *AlertTemplateService) Purge(ctx context.Context, id string) error {
	return s.templateRepo.Purge(ctx, id)
}

// Restore restores a soft-deleted alert template
func (s *AlertTemplateService) Restore(ctx context.Context, id string) error {
	return s.templateRepo.Restore(ctx, id)
}

// List retrieves a paginated list of alert templates
func (s *AlertTemplateService) List(ctx context.Context, pagination action.Pagination) (action.ListResult[action.AlertTemplateResult], error) {
	templates, total, err := s.templateRepo.List(ctx, pagination.Page, pagination.Limit)
	if err != nil {
		return action.ListResult[action.AlertTemplateResult]{}, err
	}

	results := action.NewAlertTemplateResultList(templates)
	return action.NewListResult(results, pagination, total), nil
}

// GetBySeverity retrieves alert templates by severity
func (s *AlertTemplateService) GetBySeverity(ctx context.Context, severity domain.AlertSeverity) ([]action.AlertTemplateResult, error) {
	if !severity.IsValid() {
		return nil, domainerrors.NewValidationError("severity", "invalid severity value")
	}
	templates, err := s.templateRepo.GetBySeverity(ctx, severity)
	if err != nil {
		return nil, err
	}
	return action.NewAlertTemplateResultList(templates), nil
}
