-- Rollback initial schema

DROP TABLE IF EXISTS bootstrap_tokens CASCADE;
DROP TABLE IF EXISTS check_settings CASCADE;
DROP TABLE IF EXISTS alert_rules CASCADE;
DROP TABLE IF EXISTS alert_templates CASCADE;
DROP TABLE IF EXISTS exporters CASCADE;
DROP TABLE IF EXISTS target_secondary_groups CASCADE;
DROP TABLE IF EXISTS targets CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
